tcp:
	gcc tcp_server.c -o tcp_server
	gcc tcp_client.c -o tcp_client

tcp-loop:
	gcc tcp_loop_server.c -o tcp_loop_server
	gcc tcp_loop_client.c -o tcp_loop_client

tcp-mu:
	gcc tcp_mu_server.c -o tcp_mu_server
	gcc tcp_mu_client.c -o tcp_mu_client

udp:
	gcc udp_server.c -o udp_server
	gcc udp_client.c -o udp_client

ftp:
	gcc ftp_server.c -o ftp_server
	gcc ftp_client.c -o ftp_client

clean:
	-rm -rf tcp_server tcp_client tcp_loop_server tcp_loop_client \
		ftp_server ftp_client